# Generated by Django 3.1 on 2021-08-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210803_2003"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="api.Recipeingredient", to="api.Ingredient"
            ),
        ),
    ]
