# Generated by Django 3.1 on 2021-08-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
