repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: 'setup.cfg'
      - id: end-of-file-fixer
        exclude: 'setup.cfg'
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        args: ['--py38-plus']

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
        'flake8-blind-except',
        'flake8-bandit',
        'flake8-comprehensions',
        'flake8-mutable',
        'flake8-bugbear',
        'flake8-broken-line',
        'flake8-print',
        'flake8-logging-format',
        'flake8-pytest-style',
        ]

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    -   id: pylint
        args: [
        # only errors
        "-E",
        "--disable=import-error"
        ]
