# Generated by Django 3.1 on 2021-08-08 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210726_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(through='users.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
